// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGeniusLyrics(arg1:string):Promise<string>;

export function GetSpotifyRecommendations(arg1:string):Promise<string>;

export function Predict(arg1:string):Promise<string>;
